replacing wire MVU CSR interface with APB, adding dependency IPs from…
obilaniu/MVU pull request #39
Opened 2022-07-16 02:55 UTC by hossein1387

This PR changes the MVU configuration interface entirely:

1. Replacing wire MVU CSR interface with APB.
2. Adding dependency IPs from Pulp: 
           - APB Interface: https://github.com/pulp-platform/apb
           - Common-Cells: https://github.com/pulp-platform/common_cells 
4. Restructuring MVU to use APB interface by wrapping MVU top with an APB to register translator layer.
5. Splitting MVU config and MVU external interfaces.
6. Adding APB driver to the testbench. Writing to MVU configuration registers is possible either through APB or from backdoor (HDL hierarchy path).
7. Automating generating cSRs C header files and SystemVerilog enums in mvu_pkg

2022-07-25 18:59 UTC, wagnersj requested changes

2022-07-26 17:04 UTC, hossein1387 commented on verification/scripts/mvu.tcl
> +set_property display_limit 40000000 [current_wave_config]
I use this script to let Vivado know which signals I am interested in to view in waveform. PITO, BARVINN and MVU all have their own waveform script. I think we should keep them.

2022-07-27 01:40 UTC, hossein1387 commented on verilog/mvutop_wrapper.sv
> +            mvu_pkg::CSR_MVUUSEHPADDER      : mvu_cfg_if.usehpadder[mvu_id] = apb.pwdata[0];
I agree, I will keep it like this for now. Once high precision RAMs are fully integrated, we can define the bit fields of a `highprecision_config` register properly.

2022-08-05 13:32 UTC, wagnersj approved these changes

2022-08-05 18:19 UTC, merged