Conflict detect fixes
obilaniu/MVU pull request #47
Opened 2022-10-07 17:58 UTC by obilaniu

2023-10-27 18:11 UTC, wagnersj commented
Finished testbenches. Ready for review.

2023-10-27 21:21 UTC, wagnersj commented on verilog/mvu.v
> +                                      (rdd_grnt & rdd_bankhit) ? rdd_addr : rdc_addr);
We get a syntax error here. Need an opening bracket on the second line of this statement.

2023-10-27 21:21 UTC, wagnersj commented on verilog/mvu.v
> +                                      (rdd_grnt & rdd_bankhit) ?     2'd1 : 2'd2);
We get a syntax error here. Need an opening bracket on the second line of this statement.

2023-10-27 21:22 UTC, wagnersj approved these changes

2023-11-04 03:08 UTC, hossein1387 requested changes
The rest of the PR looks good to me

2023-11-04 03:08 UTC, hossein1387 commented on verification/lib/testbench/testbench_base.sv
> +        return 1024*bank + offset;
Where does the 1024 comes from?

2023-11-10 21:04 UTC, wagnersj commented on verification/lib/testbench/testbench_base.sv
> +        return 1024*bank + offset;
Addressed in commit 9cc80c3

2023-11-10 21:05 UTC, wagnersj approved these changes

2023-11-10 21:41 UTC, hossein1387 approved these changes

2023-11-13 14:21 UTC, merged